export const inpSignup = [
  {
    id: 1,
    name: "firstName",
    type: "text",
    placeholder: "First Name",
    errorMessage: "Name should be 3-16 char long",
    label: "First Name",
    pattern: "^[A-Za-z0-9]{3,16}$",
    required: true,
  },
  {
    id: 2,
    name: "lastName",
    type: "text",
    placeholder: "Last Name",
    errorMessage: "Name should be 3-16 char long",
    label: "Last Name",
    pattern: "^[A-Za-z0-9]{3,16}$",
    required: true,
  },
  {
    id: 3,
    name: "email",
    type: "text",
    placeholder: "Email",
    errorMessage: "It should be a valid email",
    label: "Email",
    required: true,
  },
  {
    id: 4,
    name: "password",
    type: "password",
    placeholder: "Password",
    errorMessage: "Password should be 8-20 characters",
    label: "Password",
    required: true,
  },
  {
    id: 5,
    name: "confirmPassword",
    type: "password",
    placeholder: "Confirm Password",
    errorMessage: "Password don't match",
    label: "Confirm Password",
    required: true,
  },
];

export const inpLogin = [
  {
    id: 1,
    name: "email",
    type: "text",
    placeholder: "Email",
    errorMessage: "It should be a valid email",
    label: "Email",
    required: true,
  },
  {
    id: 2,
    name: "password",
    type: "password",
    placeholder: "Password",
    errorMessage: "Password should be 8-20 characters",
    label: "Password",
    required: true,
  },
];
